import Head from "next/head";
// import Image from "next/image";
import styles from "@/styles/Home.module.css";
// import Link from "next/link";
// import Navbar from "../../components/Navbar/Navbar";
// import { UserState } from "@/redux/reducers/usersReducer";
// import { useDispatch, useSelector } from "react-redux";
// import { addUser } from "@/redux/reducers/usersReducer";
// import { RootState } from "../../Types/types";
// import { ChangeEvent, useState } from "react";
// import AddUserToGroup from "../../components/AddUserToGroup/AddUserToGroup";
import MyGroup from "../../components/MyGroup/MyGroup";

export default function Home() {
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Expense Mate</h1>
        <MyGroup />
      </main>
    </>
  );
}
